# Generated by Django 4.1.3 on 2022-11-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_place1'),
    ]

    operations = [
        migrations.AddField(
            model_name='place1',
            name='cust',
            field=models.TextField(default=10),
            preserve_default=False,
        ),
    ]
